name: test

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Update and Install apt Dependencies
        run: |
          sudo apt update
          sudo apt install -y jq

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --progress-bar off -U pip
          python3 -m pip install --progress-bar off -U .[tests]

      - name: echo pip list
        run: |
          python3 -m pip list

      - name: env
        run: |
          env

      - name: Run mod
        run: |
          python3 -c "from test_pkg.mod import fork_run; fork_run()"

      - name: Run pytest
        run: |
          pytest -s
